alias reloadz='. ~/.zshrc'
alias stt='subl .'
alias st='subl '
alias dotos='subl ~/.dotfiles'
alias at='atom'
alias open='nautilus -n . 2> /dev/null'						#Open nautilus in current dir
alias bootstrap='~/.dotfiles/script/bootstrap'
alias dotfiles='cd ~/.dotfiles'
alias zeves='/opt/Z/Z-Eves/system/z-eves-gui.sh &' #ZEVES access... 