alias reload='. ~/.zshrc && echo "ZSH config reloaded from ~/.zshrc"'
alias stt='LANG=en_US.UTF-8 subl .'
alias st='LANG=en_US.UTF-8 subl'
alias dotos='atom $ZSH'
alias at='atom'
alias bootstrap='$ZSH/script/bootstrap'
alias dotfiles='cd $ZSH'
